services:
  db:
    image: postgres
    container_name : db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev

  api : 
    build :  ./backend
    container_name : api
    image : api
    depends_on : 
      - 'db'
    ports :
      - "8000:8000" 
    tty : true
    env_file:
      - ./.env.dev

  frontend :
    build : ./apache
    container_name : app
    image : app
    tty : true
    ports: 
      - "8080:80"