services:
  db:
    image: postgres
    container_name : db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web : 
    build :  ./backend
    container_name : api
    image : api
    depends_on : 
      - 'db'
    ports :
      - "8000:8000" 
    tty : true
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  asset-tracker :
    build : ./apache
    container_name : app
    image : app
    tty : true
    ports: 
      - "8080:80"


  

    
      


