# Generated by Django 4.0.4 on 2022-06-10 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_tag', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('checked_in', models.BooleanField(verbose_name=0)),
                ('checked_in_count', models.IntegerField(verbose_name=0)),
                ('last_checked_in', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('last_checked_out', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(max_length=7)),
                ('time_stamp', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('issue', models.CharField(max_length=300)),
            ],
        ),
    ]
